# Generated by Django 5.0.14 on 2026-08-22 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='currency',
            field=models.CharField(default='INR', max_length=3),
        ),
    ]
