"""
Seed data for GlobeTrotter - the city and activity catalogue.
Author: Margish

Load it with the management command:

    python manage.py seed_travel_data            # catalogue only
    python manage.py seed_travel_data --reset    # wipe the catalogue first
    python manage.py seed_travel_data --demo     # also build the demo trip

Both seed_data() and seed_demo_trip() are safe to re-run.
"""

from datetime import date, time, timedelta

CITIES_DATA = [
    # Asia
    {
        'name': 'Tokyo',
        'country': 'Japan',
        'description': 'A fascinating blend of ultra-modern and traditional, from neon-lit skyscrapers to historic temples.',
        'cost_index': 4,
        'popularity': 95,
        'avg_hotel_cost': 120.00,
        'avg_meal_cost': 25.00,
        'avg_transport_cost': 15.00,
        'latitude': 35.6762,
        'longitude': 139.6503,
        'image_url': 'https://images.unsplash.com/photo-1540959733332-eab4deabeeaf?w=800',
    },
    {
        'name': 'Bangkok',
        'country': 'Thailand',
        'description': 'Vibrant street life, ornate temples, and world-famous cuisine at budget-friendly prices.',
        'cost_index': 2,
        'popularity': 90,
        'avg_hotel_cost': 40.00,
        'avg_meal_cost': 8.00,
        'avg_transport_cost': 5.00,
        'latitude': 13.7563,
        'longitude': 100.5018,
        'image_url': 'https://images.unsplash.com/photo-1508009603885-50cf7c579365?w=800',
    },
    {
        'name': 'Singapore',
        'country': 'Singapore',
        'description': 'A gleaming metropolis with stunning architecture, diverse food scene, and lush gardens.',
        'cost_index': 4,
        'popularity': 88,
        'avg_hotel_cost': 150.00,
        'avg_meal_cost': 20.00,
        'avg_transport_cost': 12.00,
        'latitude': 1.3521,
        'longitude': 103.8198,
        'image_url': 'https://images.unsplash.com/photo-1525625293386-3f8f99389edd?w=800',
    },
    {
        'name': 'Bali',
        'country': 'Indonesia',
        'description': 'Tropical paradise with beautiful beaches, rice terraces, and rich cultural heritage.',
        'cost_index': 2,
        'popularity': 92,
        'avg_hotel_cost': 50.00,
        'avg_meal_cost': 10.00,
        'avg_transport_cost': 8.00,
        'latitude': -8.3405,
        'longitude': 115.0920,
        'image_url': 'https://images.unsplash.com/photo-1537996194471-e657df975ab4?w=800',
    },
    {
        'name': 'Dubai',
        'country': 'UAE',
        'description': 'Futuristic skyline, luxury shopping, and desert adventures in the heart of the Middle East.',
        'cost_index': 5,
        'popularity': 85,
        'avg_hotel_cost': 180.00,
        'avg_meal_cost': 35.00,
        'avg_transport_cost': 20.00,
        'latitude': 25.2048,
        'longitude': 55.2708,
        'image_url': 'https://images.unsplash.com/photo-1512453979798-5ea266f8880c?w=800',
    },

    # Europe
    {
        'name': 'Paris',
        'country': 'France',
        'description': 'The City of Light, famous for art, fashion, cuisine, and iconic landmarks like the Eiffel Tower.',
        'cost_index': 4,
        'popularity': 98,
        'avg_hotel_cost': 150.00,
        'avg_meal_cost': 30.00,
        'avg_transport_cost': 15.00,
        'latitude': 48.8566,
        'longitude': 2.3522,
        'image_url': 'https://images.unsplash.com/photo-1502602898657-3e91760cbb34?w=800',
    },
    {
        'name': 'Rome',
        'country': 'Italy',
        'description': 'The Eternal City with ancient ruins, Renaissance art, and incredible Italian cuisine.',
        'cost_index': 3,
        'popularity': 94,
        'avg_hotel_cost': 100.00,
        'avg_meal_cost': 25.00,
        'avg_transport_cost': 10.00,
        'latitude': 41.9028,
        'longitude': 12.4964,
        'image_url': 'https://images.unsplash.com/photo-1552832230-c0197dd311b5?w=800',
    },
    {
        'name': 'Barcelona',
        'country': 'Spain',
        'description': 'Gaudi architecture, Mediterranean beaches, and vibrant nightlife in Catalonia.',
        'cost_index': 3,
        'popularity': 91,
        'avg_hotel_cost': 90.00,
        'avg_meal_cost': 22.00,
        'avg_transport_cost': 10.00,
        'latitude': 41.3851,
        'longitude': 2.1734,
        'image_url': 'https://images.unsplash.com/photo-1583422409516-2895a77efded?w=800',
    },
    {
        'name': 'Amsterdam',
        'country': 'Netherlands',
        'description': 'Picturesque canals, world-class museums, and a unique cycling culture.',
        'cost_index': 4,
        'popularity': 87,
        'avg_hotel_cost': 130.00,
        'avg_meal_cost': 28.00,
        'avg_transport_cost': 8.00,
        'latitude': 52.3676,
        'longitude': 4.9041,
        'image_url': 'https://images.unsplash.com/photo-1534351590666-13e3e96b5017?w=800',
    },
    {
        'name': 'London',
        'country': 'United Kingdom',
        'description': 'Historic landmarks, royal palaces, world-class theater, and diverse neighborhoods.',
        'cost_index': 5,
        'popularity': 96,
        'avg_hotel_cost': 180.00,
        'avg_meal_cost': 35.00,
        'avg_transport_cost': 18.00,
        'latitude': 51.5074,
        'longitude': -0.1278,
        'image_url': 'https://images.unsplash.com/photo-1513635269975-59663e0ac1ad?w=800',
    },
    {
        'name': 'Prague',
        'country': 'Czech Republic',
        'description': 'Fairy-tale old town, gothic architecture, and excellent beer at affordable prices.',
        'cost_index': 2,
        'popularity': 82,
        'avg_hotel_cost': 60.00,
        'avg_meal_cost': 15.00,
        'avg_transport_cost': 5.00,
        'latitude': 50.0755,
        'longitude': 14.4378,
        'image_url': 'https://images.unsplash.com/photo-1541849546-216549ae216d?w=800',
    },
    {
        'name': 'Istanbul',
        'country': 'Turkey',
        'description': 'Where East meets West, with stunning mosques, bazaars, and Bosphorus views.',
        'cost_index': 2,
        'popularity': 84,
        'avg_hotel_cost': 55.00,
        'avg_meal_cost': 12.00,
        'avg_transport_cost': 5.00,
        'latitude': 41.0082,
        'longitude': 28.9784,
        'image_url': 'https://images.unsplash.com/photo-1524231757912-21f4fe3a7200?w=800',
    },

    # Americas
    {
        'name': 'New York',
        'country': 'USA',
        'description': 'The city that never sleeps, with iconic skyline, Broadway, and endless attractions.',
        'cost_index': 5,
        'popularity': 97,
        'avg_hotel_cost': 200.00,
        'avg_meal_cost': 40.00,
        'avg_transport_cost': 15.00,
        'latitude': 40.7128,
        'longitude': -74.0060,
        'image_url': 'https://images.unsplash.com/photo-1496442226666-8d4d0e62e6e9?w=800',
    },
    {
        'name': 'Mexico City',
        'country': 'Mexico',
        'description': 'Rich history, vibrant culture, incredible food, and world-class museums.',
        'cost_index': 2,
        'popularity': 78,
        'avg_hotel_cost': 50.00,
        'avg_meal_cost': 12.00,
        'avg_transport_cost': 5.00,
        'latitude': 19.4326,
        'longitude': -99.1332,
        'image_url': 'https://images.unsplash.com/photo-1585464231875-d9ef1f5ad396?w=800',
    },
    {
        'name': 'Rio de Janeiro',
        'country': 'Brazil',
        'description': 'Stunning beaches, iconic Christ the Redeemer, and infectious samba rhythms.',
        'cost_index': 3,
        'popularity': 80,
        'avg_hotel_cost': 70.00,
        'avg_meal_cost': 18.00,
        'avg_transport_cost': 8.00,
        'latitude': -22.9068,
        'longitude': -43.1729,
        'image_url': 'https://images.unsplash.com/photo-1483729558449-99ef09a8c325?w=800',
    },

    # Oceania
    {
        'name': 'Sydney',
        'country': 'Australia',
        'description': 'Iconic Opera House, beautiful harbor, stunning beaches, and laid-back lifestyle.',
        'cost_index': 4,
        'popularity': 86,
        'avg_hotel_cost': 140.00,
        'avg_meal_cost': 30.00,
        'avg_transport_cost': 15.00,
        'latitude': -33.8688,
        'longitude': 151.2093,
        'image_url': 'https://images.unsplash.com/photo-1506973035872-a4ec16b8e8d9?w=800',
    },

    # Africa
    {
        'name': 'Cape Town',
        'country': 'South Africa',
        'description': 'Stunning Table Mountain, beautiful beaches, wine country, and diverse wildlife.',
        'cost_index': 2,
        'popularity': 75,
        'avg_hotel_cost': 60.00,
        'avg_meal_cost': 15.00,
        'avg_transport_cost': 10.00,
        'latitude': -33.9249,
        'longitude': 18.4241,
        'image_url': 'https://images.unsplash.com/photo-1580060839134-75a5edca2e99?w=800',
    },
    {
        'name': 'Marrakech',
        'country': 'Morocco',
        'description': 'Vibrant souks, stunning palaces, and the gateway to the Sahara Desert.',
        'cost_index': 2,
        'popularity': 76,
        'avg_hotel_cost': 45.00,
        'avg_meal_cost': 10.00,
        'avg_transport_cost': 5.00,
        'latitude': 31.6295,
        'longitude': -7.9811,
        'image_url': 'https://images.unsplash.com/photo-1597212720452-7c4b7b7b6b9e?w=800',
    },

    # India
    {
        'name': 'Mumbai',
        'country': 'India',
        'description': 'Bollywood capital, historic landmarks, street food paradise, and vibrant nightlife.',
        'cost_index': 2,
        'popularity': 79,
        'avg_hotel_cost': 50.00,
        'avg_meal_cost': 8.00,
        'avg_transport_cost': 5.00,
        'latitude': 19.0760,
        'longitude': 72.8777,
        'image_url': 'https://images.unsplash.com/photo-1570168007204-dfb528c6958f?w=800',
    },
    {
        'name': 'Jaipur',
        'country': 'India',
        'description': 'The Pink City with magnificent palaces, forts, and rich Rajasthani culture.',
        'cost_index': 1,
        'popularity': 72,
        'avg_hotel_cost': 35.00,
        'avg_meal_cost': 6.00,
        'avg_transport_cost': 4.00,
        'latitude': 26.9124,
        'longitude': 75.7873,
        'image_url': 'https://images.unsplash.com/photo-1477587458883-47145ed94245?w=800',
    },
    {
        'name': 'Delhi',
        'country': 'India',
        'description': "India's capital: Mughal monuments, Lutyens boulevards and Old Delhi food lanes.",
        'cost_index': 2,
        'popularity': 81,
        'avg_hotel_cost': 42.00,
        'avg_meal_cost': 7.00,
        'avg_transport_cost': 4.00,
        'latitude': 28.6139,
        'longitude': 77.2090,
        'image_url': 'https://images.unsplash.com/photo-1587474260584-136574528ed5?w=800',
    },
    {
        'name': 'Ahmedabad',
        'country': 'India',
        'description': "UNESCO World Heritage City with stepwells, Gandhi's ashram and legendary street food.",
        'cost_index': 1,
        'popularity': 68,
        'avg_hotel_cost': 30.00,
        'avg_meal_cost': 5.00,
        'avg_transport_cost': 3.00,
        'latitude': 23.0225,
        'longitude': 72.5714,
        'image_url': 'https://images.unsplash.com/photo-1621996346565-e3dbc646d9a9?w=800',
    },
    {
        'name': 'Goa',
        'country': 'India',
        'description': "Beaches, Portuguese-era churches, spice plantations and India's most relaxed nightlife.",
        'cost_index': 2,
        'popularity': 87,
        'avg_hotel_cost': 45.00,
        'avg_meal_cost': 9.00,
        'avg_transport_cost': 6.00,
        'latitude': 15.2993,
        'longitude': 74.1240,
        'image_url': 'https://images.unsplash.com/photo-1512343879784-a960bf40e7f2?w=800',
    },
    {
        'name': 'Udaipur',
        'country': 'India',
        'description': 'The City of Lakes: palaces on the water, havelis and Aravalli sunsets.',
        'cost_index': 2,
        'popularity': 74,
        'avg_hotel_cost': 40.00,
        'avg_meal_cost': 7.00,
        'avg_transport_cost': 4.00,
        'latitude': 24.5854,
        'longitude': 73.7125,
        'image_url': 'https://images.unsplash.com/photo-1568495248636-6432b97bd949?w=800',
    },
    {
        'name': 'Bengaluru',
        'country': 'India',
        'description': 'Garden city and tech capital, with craft breweries, parks and palace grounds.',
        'cost_index': 2,
        'popularity': 70,
        'avg_hotel_cost': 45.00,
        'avg_meal_cost': 8.00,
        'avg_transport_cost': 5.00,
        'latitude': 12.9716,
        'longitude': 77.5946,
        'image_url': 'https://images.unsplash.com/photo-1596176530529-78163a4f7af2?w=800',
    },
    {
        'name': 'Agra',
        'country': 'India',
        'description': 'Home of the Taj Mahal, Agra Fort and the abandoned city of Fatehpur Sikri.',
        'cost_index': 1,
        'popularity': 83,
        'avg_hotel_cost': 32.00,
        'avg_meal_cost': 6.00,
        'avg_transport_cost': 4.00,
        'latitude': 27.1767,
        'longitude': 78.0081,
        'image_url': 'https://images.unsplash.com/photo-1564507592333-c60657eea523?w=800',
    },
    {
        'name': 'Lonavala',
        'country': 'India',
        'description': 'Monsoon hill station in the Sahyadris: waterfalls, forts and easy Mumbai escapes.',
        'cost_index': 1,
        'popularity': 58,
        'avg_hotel_cost': 28.00,
        'avg_meal_cost': 5.00,
        'avg_transport_cost': 3.00,
        'latitude': 18.7546,
        'longitude': 73.4062,
        'image_url': 'https://images.unsplash.com/photo-1595815771614-ade9d652a65d?w=800',
    },
]

ACTIVITY_TYPES = [
    {'name': 'sightseeing', 'icon': 'fa-camera'},
    {'name': 'adventure', 'icon': 'fa-mountain'},
    {'name': 'cultural', 'icon': 'fa-landmark'},
    {'name': 'food', 'icon': 'fa-utensils'},
    {'name': 'shopping', 'icon': 'fa-shopping-bag'},
    {'name': 'relaxation', 'icon': 'fa-spa'},
    {'name': 'nightlife', 'icon': 'fa-glass-cheers'},
    {'name': 'nature', 'icon': 'fa-leaf'},
    {'name': 'sports', 'icon': 'fa-futbol'},
    {'name': 'entertainment', 'icon': 'fa-ticket-alt'},
]

# Activities organized by city
ACTIVITIES_DATA = {
    'Paris': [
        {
            'name': 'Eiffel Tower Visit',
            'activity_type': 'sightseeing',
            'description': 'Iconic iron lattice tower with panoramic city views from multiple levels.',
            'cost': 26.00,
            'duration_hours': 3.0,
            'rating': 4.8,
            'popularity': 98,
            'best_time': 'Evening',
        },
        {
            'name': 'Louvre Museum',
            'activity_type': 'cultural',
            'description': 'World\'s largest art museum, home to the Mona Lisa and countless masterpieces.',
            'cost': 17.00,
            'duration_hours': 4.0,
            'rating': 4.9,
            'popularity': 96,
            'best_time': 'Morning',
        },
        {
            'name': 'Seine River Cruise',
            'activity_type': 'sightseeing',
            'description': 'Scenic boat tour along the Seine, passing major landmarks.',
            'cost': 15.00,
            'duration_hours': 1.5,
            'rating': 4.6,
            'popularity': 88,
            'best_time': 'Evening',
        },
        {
            'name': 'Montmartre Walking Tour',
            'activity_type': 'cultural',
            'description': 'Explore the artistic neighborhood with Sacré-Cœur and charming streets.',
            'cost': 0.00,
            'duration_hours': 2.5,
            'rating': 4.5,
            'popularity': 82,
            'best_time': 'Afternoon',
        },
        {
            'name': 'French Cooking Class',
            'activity_type': 'food',
            'description': 'Learn to make classic French dishes with a professional chef.',
            'cost': 85.00,
            'duration_hours': 3.0,
            'rating': 4.8,
            'popularity': 75,
            'best_time': 'Morning',
        },
    ],
    'Tokyo': [
        {
            'name': 'Senso-ji Temple Visit',
            'activity_type': 'cultural',
            'description': 'Tokyo\'s oldest temple with traditional shopping street.',
            'cost': 0.00,
            'duration_hours': 2.0,
            'rating': 4.7,
            'popularity': 94,
            'best_time': 'Morning',
        },
        {
            'name': 'Shibuya Crossing Experience',
            'activity_type': 'sightseeing',
            'description': 'World\'s busiest pedestrian crossing and vibrant shopping district.',
            'cost': 0.00,
            'duration_hours': 2.0,
            'rating': 4.5,
            'popularity': 92,
            'best_time': 'Evening',
        },
        {
            'name': 'Tsukiji Outer Market Food Tour',
            'activity_type': 'food',
            'description': 'Fresh sushi, street food, and culinary delights at the famous market.',
            'cost': 50.00,
            'duration_hours': 3.0,
            'rating': 4.8,
            'popularity': 90,
            'best_time': 'Morning',
        },
        {
            'name': 'Tokyo Skytree',
            'activity_type': 'sightseeing',
            'description': 'Observation deck with stunning views from Japan\'s tallest tower.',
            'cost': 18.00,
            'duration_hours': 2.0,
            'rating': 4.6,
            'popularity': 85,
            'best_time': 'Evening',
        },
        {
            'name': 'Akihabara Electronics & Anime',
            'activity_type': 'shopping',
            'description': 'Electronics paradise and anime culture capital.',
            'cost': 0.00,
            'duration_hours': 3.0,
            'rating': 4.4,
            'popularity': 82,
            'best_time': 'Afternoon',
        },
    ],
    'New York': [
        {
            'name': 'Statue of Liberty & Ellis Island',
            'activity_type': 'sightseeing',
            'description': 'Iconic symbol of freedom with immigration museum.',
            'cost': 24.00,
            'duration_hours': 5.0,
            'rating': 4.7,
            'popularity': 95,
            'best_time': 'Morning',
        },
        {
            'name': 'Central Park Walking Tour',
            'activity_type': 'nature',
            'description': 'Explore the famous urban oasis with guides.',
            'cost': 0.00,
            'duration_hours': 2.5,
            'rating': 4.6,
            'popularity': 90,
            'best_time': 'Morning',
        },
        {
            'name': 'Broadway Show',
            'activity_type': 'entertainment',
            'description': 'World-class theater experience in Times Square.',
            'cost': 120.00,
            'duration_hours': 3.0,
            'rating': 4.9,
            'popularity': 92,
            'best_time': 'Evening',
        },
        {
            'name': 'Metropolitan Museum of Art',
            'activity_type': 'cultural',
            'description': 'One of the world\'s greatest art museums.',
            'cost': 25.00,
            'duration_hours': 4.0,
            'rating': 4.8,
            'popularity': 88,
            'best_time': 'Afternoon',
        },
        {
            'name': 'High Line Walk',
            'activity_type': 'nature',
            'description': 'Elevated park built on historic freight rail lines.',
            'cost': 0.00,
            'duration_hours': 1.5,
            'rating': 4.5,
            'popularity': 80,
            'best_time': 'Afternoon',
        },
    ],
    'London': [
        {
            'name': 'Tower of London',
            'activity_type': 'cultural',
            'description': 'Historic castle with Crown Jewels and Beefeater tours.',
            'cost': 30.00,
            'duration_hours': 3.0,
            'rating': 4.7,
            'popularity': 93,
            'best_time': 'Morning',
        },
        {
            'name': 'British Museum',
            'activity_type': 'cultural',
            'description': 'World-famous museum with artifacts from around the globe.',
            'cost': 0.00,
            'duration_hours': 4.0,
            'rating': 4.8,
            'popularity': 91,
            'best_time': 'Afternoon',
        },
        {
            'name': 'West End Show',
            'activity_type': 'entertainment',
            'description': 'London\'s famous theater district experience.',
            'cost': 80.00,
            'duration_hours': 3.0,
            'rating': 4.8,
            'popularity': 88,
            'best_time': 'Evening',
        },
        {
            'name': 'Borough Market Food Tour',
            'activity_type': 'food',
            'description': 'London\'s oldest food market with artisan producers.',
            'cost': 35.00,
            'duration_hours': 2.5,
            'rating': 4.6,
            'popularity': 82,
            'best_time': 'Morning',
        },
        {
            'name': 'Buckingham Palace & Changing of Guard',
            'activity_type': 'sightseeing',
            'description': 'See the famous ceremony at the royal residence.',
            'cost': 0.00,
            'duration_hours': 2.0,
            'rating': 4.5,
            'popularity': 90,
            'best_time': 'Morning',
        },
    ],
    'Rome': [
        {
            'name': 'Colosseum Tour',
            'activity_type': 'cultural',
            'description': 'Ancient Roman amphitheater with guided history tour.',
            'cost': 18.00,
            'duration_hours': 3.0,
            'rating': 4.8,
            'popularity': 97,
            'best_time': 'Morning',
        },
        {
            'name': 'Vatican Museums & Sistine Chapel',
            'activity_type': 'cultural',
            'description': 'Magnificent art collection and Michelangelo\'s masterpiece.',
            'cost': 20.00,
            'duration_hours': 4.0,
            'rating': 4.9,
            'popularity': 95,
            'best_time': 'Morning',
        },
        {
            'name': 'Trastevere Food Walk',
            'activity_type': 'food',
            'description': 'Authentic Roman cuisine in charming neighborhood.',
            'cost': 65.00,
            'duration_hours': 3.0,
            'rating': 4.7,
            'popularity': 85,
            'best_time': 'Evening',
        },
        {
            'name': 'Trevi Fountain & Spanish Steps',
            'activity_type': 'sightseeing',
            'description': 'Iconic baroque fountain and famous stairway.',
            'cost': 0.00,
            'duration_hours': 1.5,
            'rating': 4.6,
            'popularity': 92,
            'best_time': 'Evening',
        },
        {
            'name': 'Pasta Making Class',
            'activity_type': 'food',
            'description': 'Learn authentic Italian pasta techniques.',
            'cost': 70.00,
            'duration_hours': 3.0,
            'rating': 4.8,
            'popularity': 78,
            'best_time': 'Afternoon',
        },
    ],
    'Bangkok': [
        {
            'name': 'Grand Palace & Wat Phra Kaew',
            'activity_type': 'cultural',
            'description': 'Stunning royal palace complex with Emerald Buddha.',
            'cost': 15.00,
            'duration_hours': 3.0,
            'rating': 4.7,
            'popularity': 94,
            'best_time': 'Morning',
        },
        {
            'name': 'Chatuchak Weekend Market',
            'activity_type': 'shopping',
            'description': 'One of the world\'s largest weekend markets.',
            'cost': 0.00,
            'duration_hours': 4.0,
            'rating': 4.5,
            'popularity': 88,
            'best_time': 'Morning',
        },
        {
            'name': 'Street Food Tour',
            'activity_type': 'food',
            'description': 'Sample Bangkok\'s famous street food scene.',
            'cost': 40.00,
            'duration_hours': 3.0,
            'rating': 4.8,
            'popularity': 90,
            'best_time': 'Evening',
        },
        {
            'name': 'Wat Arun Temple',
            'activity_type': 'cultural',
            'description': 'Iconic Temple of Dawn on the Chao Phraya River.',
            'cost': 3.00,
            'duration_hours': 1.5,
            'rating': 4.6,
            'popularity': 85,
            'best_time': 'Evening',
        },
        {
            'name': 'Thai Massage Experience',
            'activity_type': 'relaxation',
            'description': 'Traditional Thai massage at top wellness centers.',
            'cost': 25.00,
            'duration_hours': 2.0,
            'rating': 4.7,
            'popularity': 82,
            'best_time': 'Afternoon',
        },
    ],
    'Bali': [
        {
            'name': 'Ubud Rice Terraces',
            'activity_type': 'nature',
            'description': 'UNESCO-listed Tegallalang Rice Terraces.',
            'cost': 5.00,
            'duration_hours': 2.0,
            'rating': 4.7,
            'popularity': 92,
            'best_time': 'Morning',
        },
        {
            'name': 'Uluwatu Temple Sunset',
            'activity_type': 'cultural',
            'description': 'Clifftop temple with traditional Kecak fire dance.',
            'cost': 10.00,
            'duration_hours': 3.0,
            'rating': 4.8,
            'popularity': 90,
            'best_time': 'Evening',
        },
        {
            'name': 'Surfing Lesson in Kuta',
            'activity_type': 'adventure',
            'description': 'Learn to surf on Bali\'s famous beaches.',
            'cost': 35.00,
            'duration_hours': 2.0,
            'rating': 4.5,
            'popularity': 85,
            'best_time': 'Morning',
        },
        {
            'name': 'Bali Swing Adventure',
            'activity_type': 'adventure',
            'description': 'Swing over the jungle with stunning views.',
            'cost': 35.00,
            'duration_hours': 2.0,
            'rating': 4.4,
            'popularity': 88,
            'best_time': 'Afternoon',
        },
        {
            'name': 'Balinese Cooking Class',
            'activity_type': 'food',
            'description': 'Learn traditional Balinese recipes with market visit.',
            'cost': 40.00,
            'duration_hours': 4.0,
            'rating': 4.7,
            'popularity': 80,
            'best_time': 'Morning',
        },
    ],
    'Dubai': [
        {
            'name': 'Burj Khalifa Observation Deck',
            'activity_type': 'sightseeing',
            'description': 'Views from the world\'s tallest building.',
            'cost': 40.00,
            'duration_hours': 2.0,
            'rating': 4.8,
            'popularity': 95,
            'best_time': 'Evening',
        },
        {
            'name': 'Desert Safari with BBQ',
            'activity_type': 'adventure',
            'description': 'Dune bashing, camel riding, and desert camp dinner.',
            'cost': 70.00,
            'duration_hours': 6.0,
            'rating': 4.7,
            'popularity': 92,
            'best_time': 'Afternoon',
        },
        {
            'name': 'Dubai Mall & Fountain Show',
            'activity_type': 'shopping',
            'description': 'World\'s largest mall with stunning fountain performances.',
            'cost': 0.00,
            'duration_hours': 4.0,
            'rating': 4.5,
            'popularity': 88,
            'best_time': 'Evening',
        },
        {
            'name': 'Old Dubai Heritage Walk',
            'activity_type': 'cultural',
            'description': 'Explore historic Al Fahidi and traditional souks.',
            'cost': 0.00,
            'duration_hours': 3.0,
            'rating': 4.4,
            'popularity': 75,
            'best_time': 'Morning',
        },
        {
            'name': 'Palm Jumeirah Tour',
            'activity_type': 'sightseeing',
            'description': 'Visit the famous man-made island and Atlantis.',
            'cost': 25.00,
            'duration_hours': 3.0,
            'rating': 4.3,
            'popularity': 80,
            'best_time': 'Afternoon',
        },
    ],
    'Barcelona': [
        {
            'name': 'Sagrada Familia',
            'activity_type': 'cultural',
            'description': 'Gaudí\'s unfinished masterpiece basilica.',
            'cost': 26.00,
            'duration_hours': 2.0,
            'rating': 4.9,
            'popularity': 96,
            'best_time': 'Morning',
        },
        {
            'name': 'Park Güell',
            'activity_type': 'sightseeing',
            'description': 'Whimsical Gaudí park with city views.',
            'cost': 10.00,
            'duration_hours': 2.0,
            'rating': 4.7,
            'popularity': 90,
            'best_time': 'Morning',
        },
        {
            'name': 'La Boqueria Market',
            'activity_type': 'food',
            'description': 'Famous food market on Las Ramblas.',
            'cost': 0.00,
            'duration_hours': 2.0,
            'rating': 4.6,
            'popularity': 88,
            'best_time': 'Morning',
        },
        {
            'name': 'Gothic Quarter Walking Tour',
            'activity_type': 'cultural',
            'description': 'Medieval streets and hidden squares.',
            'cost': 15.00,
            'duration_hours': 2.5,
            'rating': 4.5,
            'popularity': 85,
            'best_time': 'Afternoon',
        },
        {
            'name': 'Barceloneta Beach',
            'activity_type': 'relaxation',
            'description': 'Mediterranean beach with seafood restaurants.',
            'cost': 0.00,
            'duration_hours': 3.0,
            'rating': 4.4,
            'popularity': 82,
            'best_time': 'Afternoon',
        },
    ],
    'Singapore': [
        {
            'name': 'Gardens by the Bay',
            'activity_type': 'nature',
            'description': 'Futuristic gardens with Supertrees and cloud forest.',
            'cost': 28.00,
            'duration_hours': 3.0,
            'rating': 4.8,
            'popularity': 94,
            'best_time': 'Evening',
        },
        {
            'name': 'Marina Bay Sands SkyPark',
            'activity_type': 'sightseeing',
            'description': 'Observation deck with infinity pool views.',
            'cost': 23.00,
            'duration_hours': 2.0,
            'rating': 4.6,
            'popularity': 90,
            'best_time': 'Evening',
        },
        {
            'name': 'Hawker Center Food Tour',
            'activity_type': 'food',
            'description': 'Sample Singapore\'s famous hawker stall dishes.',
            'cost': 30.00,
            'duration_hours': 3.0,
            'rating': 4.8,
            'popularity': 88,
            'best_time': 'Evening',
        },
        {
            'name': 'Sentosa Island',
            'activity_type': 'entertainment',
            'description': 'Resort island with Universal Studios and beaches.',
            'cost': 50.00,
            'duration_hours': 6.0,
            'rating': 4.5,
            'popularity': 85,
            'best_time': 'Morning',
        },
        {
            'name': 'Chinatown & Little India',
            'activity_type': 'cultural',
            'description': 'Explore Singapore\'s diverse ethnic neighborhoods.',
            'cost': 0.00,
            'duration_hours': 3.0,
            'rating': 4.4,
            'popularity': 80,
            'best_time': 'Afternoon',
        },
    ],
    'Amsterdam': [
        {
            'name': 'Anne Frank House',
            'activity_type': 'cultural',
            'description': 'Historic hiding place and Holocaust museum.',
            'cost': 16.00,
            'duration_hours': 1.5,
            'rating': 4.8,
            'popularity': 92,
            'best_time': 'Morning',
        },
        {
            'name': 'Van Gogh Museum',
            'activity_type': 'cultural',
            'description': 'World\'s largest collection of Van Gogh works.',
            'cost': 20.00,
            'duration_hours': 2.5,
            'rating': 4.8,
            'popularity': 90,
            'best_time': 'Afternoon',
        },
        {
            'name': 'Canal Cruise',
            'activity_type': 'sightseeing',
            'description': 'Scenic boat tour through historic canals.',
            'cost': 15.00,
            'duration_hours': 1.5,
            'rating': 4.5,
            'popularity': 88,
            'best_time': 'Evening',
        },
        {
            'name': 'Bike Tour of Amsterdam',
            'activity_type': 'adventure',
            'description': 'Explore the city like a local on two wheels.',
            'cost': 30.00,
            'duration_hours': 3.0,
            'rating': 4.6,
            'popularity': 82,
            'best_time': 'Morning',
        },
        {
            'name': 'Jordaan Neighborhood Walk',
            'activity_type': 'sightseeing',
            'description': 'Trendy area with boutiques and cafes.',
            'cost': 0.00,
            'duration_hours': 2.0,
            'rating': 4.4,
            'popularity': 78,
            'best_time': 'Afternoon',
        },
    ],
    'Prague': [
        {
            'name': 'Prague Castle',
            'activity_type': 'cultural',
            'description': 'Largest ancient castle complex in the world.',
            'cost': 15.00,
            'duration_hours': 3.0,
            'rating': 4.7,
            'popularity': 94,
            'best_time': 'Morning',
        },
        {
            'name': 'Charles Bridge Walk',
            'activity_type': 'sightseeing',
            'description': 'Iconic Gothic bridge with baroque statues.',
            'cost': 0.00,
            'duration_hours': 1.0,
            'rating': 4.6,
            'popularity': 92,
            'best_time': 'Evening',
        },
        {
            'name': 'Old Town Square',
            'activity_type': 'sightseeing',
            'description': 'Astronomical Clock and historic architecture.',
            'cost': 0.00,
            'duration_hours': 2.0,
            'rating': 4.5,
            'popularity': 90,
            'best_time': 'Afternoon',
        },
        {
            'name': 'Czech Beer Tasting Tour',
            'activity_type': 'food',
            'description': 'Sample world-famous Czech beers.',
            'cost': 35.00,
            'duration_hours': 3.0,
            'rating': 4.7,
            'popularity': 85,
            'best_time': 'Evening',
        },
        {
            'name': 'Jewish Quarter Tour',
            'activity_type': 'cultural',
            'description': 'Historic synagogues and cemetery.',
            'cost': 14.00,
            'duration_hours': 2.0,
            'rating': 4.5,
            'popularity': 78,
            'best_time': 'Morning',
        },
    ],
    'Istanbul': [
        {
            'name': 'Hagia Sophia',
            'activity_type': 'cultural',
            'description': 'Byzantine masterpiece turned mosque.',
            'cost': 0.00,
            'duration_hours': 2.0,
            'rating': 4.8,
            'popularity': 95,
            'best_time': 'Morning',
        },
        {
            'name': 'Grand Bazaar',
            'activity_type': 'shopping',
            'description': 'One of the oldest covered markets in the world.',
            'cost': 0.00,
            'duration_hours': 3.0,
            'rating': 4.5,
            'popularity': 90,
            'best_time': 'Afternoon',
        },
        {
            'name': 'Bosphorus Cruise',
            'activity_type': 'sightseeing',
            'description': 'Scenic cruise between Europe and Asia.',
            'cost': 15.00,
            'duration_hours': 2.0,
            'rating': 4.6,
            'popularity': 88,
            'best_time': 'Evening',
        },
        {
            'name': 'Blue Mosque',
            'activity_type': 'cultural',
            'description': 'Stunning 17th-century mosque with blue tiles.',
            'cost': 0.00,
            'duration_hours': 1.0,
            'rating': 4.7,
            'popularity': 92,
            'best_time': 'Morning',
        },
        {
            'name': 'Turkish Bath Experience',
            'activity_type': 'relaxation',
            'description': 'Traditional hammam spa experience.',
            'cost': 50.00,
            'duration_hours': 2.0,
            'rating': 4.6,
            'popularity': 80,
            'best_time': 'Afternoon',
        },
    ],
    'Mumbai': [
        {
            'name': 'Gateway of India',
            'activity_type': 'sightseeing',
            'description': 'Iconic arch monument on the waterfront.',
            'cost': 0.00,
            'duration_hours': 1.0,
            'rating': 4.5,
            'popularity': 90,
            'best_time': 'Evening',
        },
        {
            'name': 'Street Food Tour',
            'activity_type': 'food',
            'description': 'Sample vada pav, pav bhaji, and local delicacies.',
            'cost': 25.00,
            'duration_hours': 3.0,
            'rating': 4.7,
            'popularity': 88,
            'best_time': 'Evening',
        },
        {
            'name': 'Elephanta Caves',
            'activity_type': 'cultural',
            'description': 'Ancient rock-cut cave temples on an island.',
            'cost': 10.00,
            'duration_hours': 5.0,
            'rating': 4.4,
            'popularity': 82,
            'best_time': 'Morning',
        },
        {
            'name': 'Bollywood Studio Tour',
            'activity_type': 'entertainment',
            'description': 'Behind-the-scenes look at Indian cinema.',
            'cost': 35.00,
            'duration_hours': 4.0,
            'rating': 4.3,
            'popularity': 75,
            'best_time': 'Afternoon',
        },
        {
            'name': 'Dharavi Slum Tour',
            'activity_type': 'cultural',
            'description': 'Ethical community tour with local guides.',
            'cost': 15.00,
            'duration_hours': 2.0,
            'rating': 4.6,
            'popularity': 70,
            'best_time': 'Morning',
        },
    ],
    'Jaipur': [
        {
            'name': 'Amber Fort',
            'activity_type': 'cultural',
            'description': 'Magnificent hilltop fort with stunning views.',
            'cost': 7.00,
            'duration_hours': 3.0,
            'rating': 4.8,
            'popularity': 95,
            'best_time': 'Morning',
        },
        {
            'name': 'Hawa Mahal',
            'activity_type': 'sightseeing',
            'description': 'Iconic Palace of Winds with honeycomb facade.',
            'cost': 2.00,
            'duration_hours': 1.0,
            'rating': 4.6,
            'popularity': 92,
            'best_time': 'Morning',
        },
        {
            'name': 'City Palace',
            'activity_type': 'cultural',
            'description': 'Royal palace complex with museum.',
            'cost': 5.00,
            'duration_hours': 2.0,
            'rating': 4.5,
            'popularity': 88,
            'best_time': 'Afternoon',
        },
        {
            'name': 'Elephant Sanctuary Visit',
            'activity_type': 'nature',
            'description': 'Ethical elephant experience and care.',
            'cost': 40.00,
            'duration_hours': 3.0,
            'rating': 4.7,
            'popularity': 80,
            'best_time': 'Morning',
        },
        {
            'name': 'Bazaar Shopping Tour',
            'activity_type': 'shopping',
            'description': 'Traditional markets with textiles and crafts.',
            'cost': 0.00,
            'duration_hours': 3.0,
            'rating': 4.4,
            'popularity': 85,
            'best_time': 'Afternoon',
        },
    ],
    'Delhi': [
        {
            'name': 'Red Fort',
            'activity_type': 'cultural',
            'description': 'Mughal sandstone fortress and the seat of emperors for two centuries.',
            'cost': 8.00,
            'duration_hours': 2.5,
            'rating': 4.6,
            'popularity': 92,
            'best_time': 'Morning',
        },
        {
            'name': 'Humayun\'s Tomb',
            'activity_type': 'cultural',
            'description': 'Garden tomb that was the blueprint for the Taj Mahal.',
            'cost': 7.00,
            'duration_hours': 2.0,
            'rating': 4.7,
            'popularity': 86,
            'best_time': 'Morning',
        },
        {
            'name': 'Qutub Minar',
            'activity_type': 'sightseeing',
            'description': 'The tallest brick minaret in the world, set in a ruined complex.',
            'cost': 7.00,
            'duration_hours': 1.5,
            'rating': 4.5,
            'popularity': 84,
            'best_time': 'Afternoon',
        },
        {
            'name': 'Old Delhi Food Walk',
            'activity_type': 'food',
            'description': 'Chandni Chowk parathas, kebabs and jalebi with a local guide.',
            'cost': 20.00,
            'duration_hours': 3.0,
            'rating': 4.8,
            'popularity': 90,
            'best_time': 'Evening',
        },
        {
            'name': 'India Gate and Rajpath Stroll',
            'activity_type': 'sightseeing',
            'description': 'War memorial and ceremonial boulevard, best after sunset.',
            'cost': 0.00,
            'duration_hours': 1.5,
            'rating': 4.4,
            'popularity': 80,
            'best_time': 'Evening',
        },
    ],
    'Ahmedabad': [
        {
            'name': 'Adalaj Stepwell',
            'activity_type': 'cultural',
            'description': 'Five-storey carved stepwell that stays cool through the Gujarat summer.',
            'cost': 3.00,
            'duration_hours': 1.5,
            'rating': 4.7,
            'popularity': 82,
            'best_time': 'Morning',
        },
        {
            'name': 'Sabarmati Ashram',
            'activity_type': 'cultural',
            'description': 'Gandhi\'s riverside home and the starting point of the Dandi March.',
            'cost': 0.00,
            'duration_hours': 1.5,
            'rating': 4.6,
            'popularity': 88,
            'best_time': 'Morning',
        },
        {
            'name': 'Manek Chowk Night Food Market',
            'activity_type': 'food',
            'description': 'Jewellery bazaar by day, legendary street food market by night.',
            'cost': 8.00,
            'duration_hours': 2.0,
            'rating': 4.7,
            'popularity': 90,
            'best_time': 'Night',
        },
        {
            'name': 'Heritage Walk of the Old City',
            'activity_type': 'sightseeing',
            'description': 'UNESCO-listed pols, havelis and carved wooden facades.',
            'cost': 5.00,
            'duration_hours': 2.5,
            'rating': 4.5,
            'popularity': 76,
            'best_time': 'Morning',
        },
        {
            'name': 'Sabarmati Riverfront Evening',
            'activity_type': 'relaxation',
            'description': 'Landscaped promenade along the river with boat rides.',
            'cost': 0.00,
            'duration_hours': 1.5,
            'rating': 4.3,
            'popularity': 70,
            'best_time': 'Evening',
        },
    ],
    'Goa': [
        {
            'name': 'Baga and Calangute Beach Day',
            'activity_type': 'relaxation',
            'description': 'The classic North Goa beach strip with shacks and water sports.',
            'cost': 0.00,
            'duration_hours': 4.0,
            'rating': 4.4,
            'popularity': 92,
            'best_time': 'Afternoon',
        },
        {
            'name': 'Dudhsagar Waterfall Jeep Safari',
            'activity_type': 'adventure',
            'description': 'Four-hundred-metre falls reached by a jeep run through the jungle.',
            'cost': 30.00,
            'duration_hours': 6.0,
            'rating': 4.7,
            'popularity': 88,
            'best_time': 'Morning',
        },
        {
            'name': 'Old Goa Churches Tour',
            'activity_type': 'cultural',
            'description': 'Basilica of Bom Jesus and Se Cathedral, both UNESCO listed.',
            'cost': 0.00,
            'duration_hours': 2.5,
            'rating': 4.5,
            'popularity': 78,
            'best_time': 'Morning',
        },
        {
            'name': 'Mandovi River Sunset Cruise',
            'activity_type': 'entertainment',
            'description': 'Live music and folk dance on the water as the sun goes down.',
            'cost': 12.00,
            'duration_hours': 1.5,
            'rating': 4.3,
            'popularity': 82,
            'best_time': 'Evening',
        },
        {
            'name': 'Spice Plantation Lunch',
            'activity_type': 'food',
            'description': 'Guided plantation walk followed by a Goan thali on banana leaf.',
            'cost': 18.00,
            'duration_hours': 3.0,
            'rating': 4.6,
            'popularity': 74,
            'best_time': 'Afternoon',
        },
    ],
    'Udaipur': [
        {
            'name': 'City Palace Udaipur',
            'activity_type': 'cultural',
            'description': 'Sprawling lakeside palace complex with courtyards and a museum.',
            'cost': 8.00,
            'duration_hours': 2.5,
            'rating': 4.8,
            'popularity': 93,
            'best_time': 'Morning',
        },
        {
            'name': 'Lake Pichola Boat Ride',
            'activity_type': 'sightseeing',
            'description': 'Sunset boat past Jag Mandir with the Aravallis behind.',
            'cost': 12.00,
            'duration_hours': 1.0,
            'rating': 4.8,
            'popularity': 95,
            'best_time': 'Evening',
        },
        {
            'name': 'Saheliyon Ki Bari',
            'activity_type': 'nature',
            'description': 'Garden of the maidens: fountains, lotus pools and marble pavilions.',
            'cost': 2.00,
            'duration_hours': 1.0,
            'rating': 4.3,
            'popularity': 70,
            'best_time': 'Morning',
        },
        {
            'name': 'Bagore Ki Haveli Dance Show',
            'activity_type': 'entertainment',
            'description': 'Nightly Rajasthani folk dance and puppetry in a lakeside haveli.',
            'cost': 5.00,
            'duration_hours': 1.5,
            'rating': 4.6,
            'popularity': 80,
            'best_time': 'Evening',
        },
        {
            'name': 'Monsoon Palace Sunset',
            'activity_type': 'sightseeing',
            'description': 'Hilltop palace with the widest view over the lake city.',
            'cost': 4.00,
            'duration_hours': 2.0,
            'rating': 4.5,
            'popularity': 76,
            'best_time': 'Evening',
        },
    ],
    'Bengaluru': [
        {
            'name': 'Lalbagh Botanical Garden',
            'activity_type': 'nature',
            'description': 'Two-hundred-year-old garden with a glass house and rock outcrop.',
            'cost': 1.00,
            'duration_hours': 2.0,
            'rating': 4.5,
            'popularity': 78,
            'best_time': 'Morning',
        },
        {
            'name': 'Bangalore Palace',
            'activity_type': 'cultural',
            'description': 'Tudor-revival palace with fortified towers and period interiors.',
            'cost': 6.00,
            'duration_hours': 1.5,
            'rating': 4.2,
            'popularity': 70,
            'best_time': 'Afternoon',
        },
        {
            'name': 'Cubbon Park Cycle Ride',
            'activity_type': 'sports',
            'description': 'Three hundred acres of shaded avenues in the middle of the city.',
            'cost': 5.00,
            'duration_hours': 2.0,
            'rating': 4.4,
            'popularity': 66,
            'best_time': 'Morning',
        },
        {
            'name': 'Craft Brewery Trail',
            'activity_type': 'nightlife',
            'description': 'Guided crawl through the microbreweries that made the city famous.',
            'cost': 35.00,
            'duration_hours': 3.5,
            'rating': 4.6,
            'popularity': 74,
            'best_time': 'Evening',
        },
        {
            'name': 'VV Puram Food Street',
            'activity_type': 'food',
            'description': 'A single lane of dosa, chaat and holige stalls, cash only.',
            'cost': 6.00,
            'duration_hours': 2.0,
            'rating': 4.7,
            'popularity': 82,
            'best_time': 'Evening',
        },
    ],
    'Agra': [
        {
            'name': 'Taj Mahal at Sunrise',
            'activity_type': 'sightseeing',
            'description': 'The marble mausoleum in the first light, before the crowds arrive.',
            'cost': 15.00,
            'duration_hours': 3.0,
            'rating': 4.9,
            'popularity': 100,
            'best_time': 'Morning',
        },
        {
            'name': 'Agra Fort',
            'activity_type': 'cultural',
            'description': 'Red sandstone fort where Shah Jahan was imprisoned within sight of the Taj.',
            'cost': 8.00,
            'duration_hours': 2.0,
            'rating': 4.6,
            'popularity': 88,
            'best_time': 'Morning',
        },
        {
            'name': 'Mehtab Bagh Sunset View',
            'activity_type': 'sightseeing',
            'description': 'Riverside garden with the classic across-the-Yamuna view of the Taj.',
            'cost': 3.00,
            'duration_hours': 1.0,
            'rating': 4.5,
            'popularity': 80,
            'best_time': 'Evening',
        },
        {
            'name': 'Fatehpur Sikri Day Trip',
            'activity_type': 'cultural',
            'description': 'Perfectly preserved Mughal capital, abandoned after only fourteen years.',
            'cost': 12.00,
            'duration_hours': 4.0,
            'rating': 4.5,
            'popularity': 74,
            'best_time': 'Morning',
        },
        {
            'name': 'Marble Inlay Workshop',
            'activity_type': 'shopping',
            'description': 'Watch artisans cut and set semi-precious stone the Mughal way.',
            'cost': 0.00,
            'duration_hours': 1.0,
            'rating': 4.2,
            'popularity': 62,
            'best_time': 'Afternoon',
        },
    ],
    'Lonavala': [
        {
            'name': 'Tiger Point Viewpoint',
            'activity_type': 'nature',
            'description': 'Cliff-edge lookout over the Sahyadri valley, spectacular in monsoon.',
            'cost': 0.00,
            'duration_hours': 1.5,
            'rating': 4.5,
            'popularity': 76,
            'best_time': 'Morning',
        },
        {
            'name': 'Bhushi Dam Monsoon Walk',
            'activity_type': 'nature',
            'description': 'Stepped spillway that turns into a natural waterslide in the rains.',
            'cost': 0.00,
            'duration_hours': 2.0,
            'rating': 4.2,
            'popularity': 80,
            'best_time': 'Afternoon',
        },
        {
            'name': 'Rajmachi Fort Trek',
            'activity_type': 'adventure',
            'description': 'Moderate ridge trek to twin forts with valley views the whole way.',
            'cost': 15.00,
            'duration_hours': 5.0,
            'rating': 4.6,
            'popularity': 70,
            'best_time': 'Morning',
        },
        {
            'name': 'Karla and Bhaja Caves',
            'activity_type': 'cultural',
            'description': 'Rock-cut Buddhist chaityas dating to the second century BCE.',
            'cost': 5.00,
            'duration_hours': 2.5,
            'rating': 4.4,
            'popularity': 64,
            'best_time': 'Morning',
        },
        {
            'name': 'Chikki Tasting Trail',
            'activity_type': 'food',
            'description': 'The brittle the hill station is named for, straight from the makers.',
            'cost': 4.00,
            'duration_hours': 1.0,
            'rating': 4.1,
            'popularity': 58,
            'best_time': 'Afternoon',
        },
    ],
    'Sydney': [
        {
            'name': 'Sydney Opera House Tour',
            'activity_type': 'cultural',
            'description': 'Backstage walk through the shells of the harbour\'s landmark.',
            'cost': 45.00,
            'duration_hours': 1.5,
            'rating': 4.7,
            'popularity': 96,
            'best_time': 'Morning',
        },
        {
            'name': 'Bondi to Coogee Coastal Walk',
            'activity_type': 'nature',
            'description': 'Six kilometres of clifftop path linking the eastern beaches.',
            'cost': 0.00,
            'duration_hours': 3.0,
            'rating': 4.8,
            'popularity': 90,
            'best_time': 'Morning',
        },
        {
            'name': 'Harbour Bridge Climb',
            'activity_type': 'adventure',
            'description': 'Summit the arch for a 360-degree view over the harbour.',
            'cost': 220.00,
            'duration_hours': 3.5,
            'rating': 4.9,
            'popularity': 85,
            'best_time': 'Afternoon',
        },
        {
            'name': 'Taronga Zoo Ferry and Visit',
            'activity_type': 'nature',
            'description': 'Australian wildlife with the skyline as a backdrop.',
            'cost': 50.00,
            'duration_hours': 4.0,
            'rating': 4.5,
            'popularity': 78,
            'best_time': 'Morning',
        },
        {
            'name': 'Sydney Fish Market Lunch',
            'activity_type': 'food',
            'description': 'Working market with oyster bars and grilled seafood counters.',
            'cost': 30.00,
            'duration_hours': 1.5,
            'rating': 4.4,
            'popularity': 72,
            'best_time': 'Afternoon',
        },
    ],
    'Cape Town': [
        {
            'name': 'Table Mountain Cableway',
            'activity_type': 'nature',
            'description': 'Rotating cable car to the flat summit above the city bowl.',
            'cost': 25.00,
            'duration_hours': 3.0,
            'rating': 4.8,
            'popularity': 96,
            'best_time': 'Morning',
        },
        {
            'name': 'Cape Peninsula Drive',
            'activity_type': 'sightseeing',
            'description': 'Chapman\'s Peak, Boulders penguins and the Cape of Good Hope.',
            'cost': 60.00,
            'duration_hours': 8.0,
            'rating': 4.8,
            'popularity': 90,
            'best_time': 'Morning',
        },
        {
            'name': 'Robben Island Ferry',
            'activity_type': 'cultural',
            'description': 'Prison island tour led by former political prisoners.',
            'cost': 35.00,
            'duration_hours': 4.0,
            'rating': 4.6,
            'popularity': 84,
            'best_time': 'Morning',
        },
        {
            'name': 'Stellenbosch Wine Tasting',
            'activity_type': 'food',
            'description': 'Cellar door tastings across the Cape winelands.',
            'cost': 55.00,
            'duration_hours': 6.0,
            'rating': 4.7,
            'popularity': 80,
            'best_time': 'Afternoon',
        },
        {
            'name': 'Kirstenbosch Gardens',
            'activity_type': 'nature',
            'description': 'Botanical garden on the mountain slopes with a canopy walkway.',
            'cost': 12.00,
            'duration_hours': 2.5,
            'rating': 4.6,
            'popularity': 74,
            'best_time': 'Morning',
        },
    ],
    'Marrakech': [
        {
            'name': 'Jemaa el-Fnaa at Dusk',
            'activity_type': 'entertainment',
            'description': 'The main square as it fills with food stalls and storytellers.',
            'cost': 0.00,
            'duration_hours': 2.0,
            'rating': 4.6,
            'popularity': 95,
            'best_time': 'Evening',
        },
        {
            'name': 'Bahia Palace',
            'activity_type': 'cultural',
            'description': 'Nineteenth-century palace of carved cedar and zellij tilework.',
            'cost': 8.00,
            'duration_hours': 1.5,
            'rating': 4.5,
            'popularity': 84,
            'best_time': 'Morning',
        },
        {
            'name': 'Souk Shopping with a Guide',
            'activity_type': 'shopping',
            'description': 'Navigate the medina for lanterns, leather and spice.',
            'cost': 15.00,
            'duration_hours': 3.0,
            'rating': 4.4,
            'popularity': 88,
            'best_time': 'Afternoon',
        },
        {
            'name': 'Agafay Desert Camel Sunset',
            'activity_type': 'adventure',
            'description': 'Stony desert ride an hour from the city, with mint tea after.',
            'cost': 40.00,
            'duration_hours': 4.0,
            'rating': 4.6,
            'popularity': 82,
            'best_time': 'Evening',
        },
        {
            'name': 'Traditional Hammam and Spa',
            'activity_type': 'relaxation',
            'description': 'Steam, black soap and a gommage scrub in a tiled bathhouse.',
            'cost': 35.00,
            'duration_hours': 2.0,
            'rating': 4.7,
            'popularity': 78,
            'best_time': 'Afternoon',
        },
    ],
    'Mexico City': [
        {
            'name': 'Teotihuacan Pyramids',
            'activity_type': 'cultural',
            'description': 'Avenue of the Dead and the Pyramid of the Sun, an hour from town.',
            'cost': 30.00,
            'duration_hours': 6.0,
            'rating': 4.8,
            'popularity': 94,
            'best_time': 'Morning',
        },
        {
            'name': 'Frida Kahlo Museum',
            'activity_type': 'cultural',
            'description': 'La Casa Azul in Coyoacan, where Kahlo lived and painted.',
            'cost': 15.00,
            'duration_hours': 2.0,
            'rating': 4.6,
            'popularity': 90,
            'best_time': 'Morning',
        },
        {
            'name': 'Xochimilco Trajinera Ride',
            'activity_type': 'entertainment',
            'description': 'Painted boats and floating mariachi on the pre-Hispanic canals.',
            'cost': 25.00,
            'duration_hours': 4.0,
            'rating': 4.5,
            'popularity': 86,
            'best_time': 'Afternoon',
        },
        {
            'name': 'Historic Centre Food Crawl',
            'activity_type': 'food',
            'description': 'Tacos al pastor, tlacoyos and churros across the Centro Historico.',
            'cost': 22.00,
            'duration_hours': 3.0,
            'rating': 4.8,
            'popularity': 88,
            'best_time': 'Evening',
        },
        {
            'name': 'Chapultepec Castle and Park',
            'activity_type': 'sightseeing',
            'description': 'Hilltop castle and the largest city park in Latin America.',
            'cost': 6.00,
            'duration_hours': 3.0,
            'rating': 4.5,
            'popularity': 76,
            'best_time': 'Morning',
        },
    ],
    'Rio de Janeiro': [
        {
            'name': 'Christ the Redeemer',
            'activity_type': 'sightseeing',
            'description': 'Cog train up Corcovado to the statue over the whole bay.',
            'cost': 25.00,
            'duration_hours': 3.0,
            'rating': 4.8,
            'popularity': 98,
            'best_time': 'Morning',
        },
        {
            'name': 'Sugarloaf Cable Car',
            'activity_type': 'sightseeing',
            'description': 'Two-stage cable car to the granite peak at the harbour mouth.',
            'cost': 30.00,
            'duration_hours': 2.5,
            'rating': 4.7,
            'popularity': 92,
            'best_time': 'Evening',
        },
        {
            'name': 'Copacabana and Ipanema Beach Day',
            'activity_type': 'relaxation',
            'description': 'The two most famous stretches of sand in Brazil, back to back.',
            'cost': 0.00,
            'duration_hours': 4.0,
            'rating': 4.6,
            'popularity': 94,
            'best_time': 'Afternoon',
        },
        {
            'name': 'Tijuca Rainforest Hike',
            'activity_type': 'nature',
            'description': 'The largest urban forest in the world, waterfalls included.',
            'cost': 35.00,
            'duration_hours': 5.0,
            'rating': 4.6,
            'popularity': 74,
            'best_time': 'Morning',
        },
        {
            'name': 'Samba Night in Lapa',
            'activity_type': 'nightlife',
            'description': 'Live samba under the Lapa arches, starting late.',
            'cost': 20.00,
            'duration_hours': 4.0,
            'rating': 4.7,
            'popularity': 84,
            'best_time': 'Night',
        },
    ],
}


def _write(stdout, message):
    if stdout is not None:
        stdout.write(message)


def seed_data(stdout=None):
    """Load activity types, cities and activities into the database.

    Idempotent - re-running it tops up anything missing instead of duplicating.

    Returns:
        dict with the counts that now exist: activity_types, cities, activities.
    """
    from travel.models import Activity, ActivityType, City

    _write(stdout, 'Creating activity types...')
    for at_data in ACTIVITY_TYPES:
        ActivityType.objects.get_or_create(
            name=at_data['name'],
            defaults={'icon': at_data['icon']},
        )

    _write(stdout, 'Creating cities...')
    city_objects = {}
    for city_data in CITIES_DATA:
        city, created = City.objects.get_or_create(
            name=city_data['name'],
            country=city_data['country'],
            defaults={
                'description': city_data.get('description', ''),
                'cost_index': city_data.get('cost_index', 3),
                'popularity': city_data.get('popularity', 50),
                'avg_hotel_cost': city_data.get('avg_hotel_cost', 50.00),
                'avg_meal_cost': city_data.get('avg_meal_cost', 15.00),
                'avg_transport_cost': city_data.get('avg_transport_cost', 10.00),
                'latitude': city_data.get('latitude'),
                'longitude': city_data.get('longitude'),
                'image_url': city_data.get('image_url'),
            },
        )
        city_objects[city.name] = city
        if created:
            _write(stdout, '  + %s, %s' % (city.name, city.country))

    _write(stdout, 'Creating activities...')
    types_by_name = {t.name: t for t in ActivityType.objects.all()}

    for city_name, activities in ACTIVITIES_DATA.items():
        city = city_objects.get(city_name)
        if city is None:
            _write(stdout, '  ! skipping activities for unknown city %s' % city_name)
            continue

        for act_data in activities:
            Activity.objects.get_or_create(
                name=act_data['name'],
                city=city,
                defaults={
                    'activity_type': types_by_name.get(act_data.get('activity_type')),
                    'description': act_data.get('description', ''),
                    'cost': act_data.get('cost', 0.00),
                    'duration_hours': act_data.get('duration_hours', 2.0),
                    'rating': act_data.get('rating', 4.0),
                    'popularity': act_data.get('popularity', 50),
                    'best_time': act_data.get('best_time'),
                },
            )

    stats = {
        'activity_types': ActivityType.objects.count(),
        'cities': City.objects.count(),
        'activities': Activity.objects.count(),
    }
    _write(stdout, 'Seeding complete.')
    return stats


# Times of day the demo activities are slotted into.
DEMO_TIMES = [time(9, 30), time(13, 0), time(17, 30)]

# The trip from section 18 of the architecture doc, ready to demo.
DEMO_TRIP = {
    'username': 'demo',
    'password': 'demo12345',
    'email': 'demo@globetrotter.test',
    'first_name': 'Demo',
    'last_name': 'Traveller',
    'trip_name': 'Goa Adventure',
    'description': 'A week along the Konkan coast: beaches, forts and a hill-station detour.',
    'budget': 2500,
    'travelers': 2,
    # (city, nights, transport mode, transport cost, hotel, per-night rate)
    'stops': [
        ('Mumbai', 2, 'Flight', 180.00, 'Colaba Boutique Stay', 65.00),
        ('Lonavala', 1, 'Train', 15.00, 'Sahyadri Hill Resort', 40.00),
        ('Goa', 4, 'Train', 25.00, 'Anjuna Beach House', 55.00),
    ],
    # Two or three activities per stop, matching the demo script.
    'activities': {
        'Mumbai': ['Gateway of India', 'Elephanta Caves', 'Street Food Tour'],
        'Lonavala': ['Tiger Point Viewpoint', 'Rajmachi Fort Trek'],
        'Goa': [
            'Baga and Calangute Beach Day',
            'Dudhsagar Waterfall Jeep Safari',
            'Mandovi River Sunset Cruise',
        ],
    },
    'expenses': [
        ('insurance', 'Travel insurance for two', 90.00),
        ('shopping', 'Souvenirs and spices', 60.00),
    ],
}


def seed_demo_trip(stdout=None, start_date=None):
    """Build the fully planned demo trip described in the architecture doc.

    Creates (or reuses) the demo user, wipes any previous demo trip of the same
    name so the demo is repeatable, then lays out stops, dates, activities and
    a couple of loose expenses.

    Returns:
        The Trip instance.
    """
    from django.contrib.auth.models import User

    from travel.models import Activity, City, Trip
    from travel.services import BudgetService, ItineraryService

    spec = DEMO_TRIP

    user, created = User.objects.get_or_create(
        username=spec['username'],
        defaults={
            'email': spec['email'],
            'first_name': spec['first_name'],
            'last_name': spec['last_name'],
        },
    )
    if created:
        user.set_password(spec['password'])
        user.save()
        _write(stdout, 'Created demo user %s' % spec['username'])

    # Rebuild from scratch so the demo always looks the same.
    Trip.objects.filter(user=user, name=spec['trip_name']).delete()

    if start_date is None:
        # Comfortably in the future so the trip shows as upcoming.
        start_date = date.today() + timedelta(days=30)

    total_nights = sum(stop[1] for stop in spec['stops'])

    trip = ItineraryService.create_trip(
        user=user,
        name=spec['trip_name'],
        description=spec['description'],
        start_date=start_date,
        end_date=start_date + timedelta(days=total_nights),
        budget=spec['budget'],
        travelers=spec['travelers'],
    )
    trip.status = 'upcoming'
    trip.is_public = True
    trip.save(update_fields=['status', 'is_public'])

    cursor = start_date
    for city_name, nights, mode, transport_cost, hotel, rate in spec['stops']:
        city = City.objects.filter(name=city_name).first()
        if city is None:
            _write(stdout, '  ! demo city %s missing, run the seeder first' % city_name)
            continue

        stop = ItineraryService.add_stop_to_trip(
            trip,
            city_id=city.id,
            arrival_date=cursor,
            departure_date=cursor + timedelta(days=nights),
            accommodation_name=hotel,
            accommodation_cost=rate,
            transport_mode=mode,
            transport_cost=transport_cost,
        )

        # Spread the stop's activities one per day from the arrival date.
        for offset, activity_name in enumerate(spec['activities'].get(city_name, [])):
            activity = Activity.objects.filter(city=city, name=activity_name).first()
            if activity is None:
                _write(stdout, '  ! demo activity missing: %s' % activity_name)
                continue
            ItineraryService.add_activity_to_stop(
                stop.id,
                activity_id=activity.id,
                scheduled_date=cursor + timedelta(days=min(offset, nights)),
                scheduled_time=DEMO_TIMES[offset % len(DEMO_TIMES)],
            )

        cursor = stop.departure_date

    for category, description, amount in spec['expenses']:
        BudgetService.add_expense(
            trip.id,
            category=category,
            description=description,
            amount=amount,
            date=start_date,
        )

    _write(stdout, 'Demo trip built: %d stops, total %s %.2f' % (
        trip.stops.count(), trip.currency, trip.get_total_cost()))
    return trip


if __name__ == '__main__':
    seed_data()
